name: 'Issue Management Action'
description: 'An action to manage issue'
author: 'Gradle'

# Define your inputs here.
inputs:
  script:
    description: 'script to run'
    required: true
  token:
    required: true
    description: 'The GitHub authentication token'
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
