name: 'Issue Management Action - Feedback'
description: 'Wait for reply or close the issue/PR'
author: 'Gradle'

inputs:
  token:
    required: true
    description: 'The GitHub authentication token'
    default: ${{ github.token }}

runs:
  using: node20
  main: ../dist/feedback/index.js
