name: 'Issue Management Action - Issue Metadata'
description: 'Ensure that issue has proper labels'
author: 'Gradle'

inputs:
  token:
    required: true
    description: 'The GitHub authentication token'
    default: ${{ github.token }}

runs:
  using: node20
  main: ../dist/issue-metadata/index.js
