name: 'Issue Management Action - Release notes'
description: 'Ensure that closed issues have release notes (or a decision about them)'
author: 'Gradle'

inputs:
  token:
    required: true
    description: 'The GitHub authentication token'
    default: ${{ github.token }}

runs:
  using: node20
  main: ../dist/release-notes/index.js
